name: send_email

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  watch:
    types: started
  workflow_dispatch:
    inputs:
      subject:
        description: '标题'
        required: true
        default: ''
      content:
        description: '内容'
        required: true
        default: ''
      user:
        description: '收件人'
        required: false
        default: '630077372@qq.com'
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Send mail'
      if: github.event_name == 'workflow_dispatch'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: ${{ github.event.inputs.subject }}
        body: ${{ github.event.inputs.content }}
        to: ${{ github.event.inputs.user }}
        from: Shaun
        content_type: text/plain
