name: robbill

on:
#   push:
#     branches: [ master ]
#   watch:
#     types: started
  workflow_dispatch:
    inputs:
      bill:
        description: '单号'
        required: true
        default: ''
      acc:
        description: '帐号'
        required: false
        default: '132'
      bind:
        description: '淘宝号'
        required: false
        default: '126317'
      sleep:
        description: '睡眠时间'
        required: false
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
     
    - name: 开始睡眠
      run: |
        python3 -c "import time;print(time.time())"
#        sleep ${{ github.event.inputs.sleep }}

#     - name: pip依赖包
#       run: |
#         pip install -r requirements.txt
        
#     - name: 抓取新站里的粉丝数据           
#       run: |
#         python3 robbill.py ${{ github.event.inputs.bill }} ${{ github.event.inputs.acc }} ${{ github.event.inputs.bind }}

#     - name: 'Send mail'
#       if: success()
#       uses: dawidd6/action-send-mail@master
#       with:
#         server_address: smtp.qq.com
#         server_port: 465
#         username: ${{ secrets.MAIL_USERNAME }}
#         password: ${{ secrets.MAIL_PASSWORD }}
#         subject: ${{ github.event.inputs.bill }}
#         body: "rob_bill结束，快来看看~"
#         to: 630077372@qq.com
#         from: Shaun_actions
#         content_type: text/plain
