name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 8 * * *
  watch:
    types: started
    
env:
  XZ_COOKIE: ${{ secrets.XZ_COOKIE }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: pip依赖包
      run: |
        pip install -r requirements.txt
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event_name: ${{ github.event_name }}"
        
    - name: 抓取新站里的粉丝数据
#       判断types方式
      if: github.event.action != 'started'   
#       if: github.event == 'watch'                   
#       直接判断执行条件
      run: |
        python3 down_fans.py
        echo "============华丽的分割线==========="
        python3 up_fans.py
      
    - name: 获取指定数据
      if: github.event.action == 'started'
      run: |
        echo "这里是获取指定日期的数据 ${{ github.event }}"    
        
    - name: 上传
      run: |
        git config --local user.email "19820637553@163.com"
        git config --local user.name "XXXShaunPan"
        git add .
        git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
        git push -u origin main && echo "push ok"
        
    - name: 'Send mail'
      if: failure()
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: CSDN Report
        body: "文件源码无变化，push失败"
        to: 630077372@qq.com
        from: Shaun_fans_actions
        content_type: text/plain
