name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 8 * * *
  watch:
    types: started
    
env:
  XZ_COOKIE: ${{ secrets.XZ_COOKIE }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: pip依赖包
      run: |
        pip install -r requirements.txt
        
    - name: 抓取新站里的粉丝数据
#       if: github.event.action != 'started'   判断types方式
      if: github.event != 'watch'                   
#       直接判断执行条件
      run: |
        python3 down_fans.py
        echo "============华丽的分割线==========="
        python3 up_fans.py
      
    - name: 获取指定数据
      if: github.event == 'watch'
      run: |
        echo "这里是获取指定日期的数据"    
        
    - name: 上传
      run: |
        git config --local user.email "19820637553@163.com"
        git config --local user.name "XXXShaunPan"
        git add .
        git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
        git push -u origin main && echo "push ok"
